<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><ApplicationIcon>Assets\FocusFence.ico</ApplicationIcon><TargetFramework>net8.0-windows</TargetFramework><UseWPF>true</UseWPF><UseWindowsForms>true</UseWindowsForms><ImplicitUsings>disable</ImplicitUsings></PropertyGroup><ItemGroup><ProjectReference Include="../FocusFence.Windows/FocusFence.Windows.csproj" /><Content Include="Admin\*.ps1" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" /></ItemGroup><ItemGroup><Resource Include="Assets\FocusFence.ico" /><None Include="Assets\FocusFence.xaml" /><Page Remove="Assets\FocusFence.xaml" /></ItemGroup></Project>
